events {}

http {
    resolver 127.0.0.11 valid=5s;
    upstream api {
        zone api 64k;
        least_conn;
        server api:8000 resolve;
    }

    server {
        listen 80;

        location /api/ {
            rewrite ^/api/(.*)$ /$1 break;
            proxy_pass http://api/;
        }

        location /health {
            proxy_pass http://api/health;
        }
    }
}